In [2]:
from collections import Counter
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

# numpy

In [3]:
# Задание: создайте вектор, заполненный нулями, размера 10, но чтобы пятый элемент был равен 1. Hint: np.zeros()

# TODO
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
# Задание: создайте матрицу 3х3 с элементами от 10 до 90 (десятками). Hint: np.arange(), np.reshape()

# TODO
matrix = np.arange(10, 100, 10)
matrix = np.reshape(matrix, (3, 3))
print (matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [7]:
# Задание: задан вектор, переверните значения элементов задом наперед
Z = np.array([[1,2,0,0,4,0]])

# TODO
#np.flip(Z)
Z[::-1]

array([[1, 2, 0, 0, 4, 0]])

In [8]:
# Задание: создайте матрицу 10х10 и заполните ее рандомными числами. Найдите элементы с минимальным и максимальным значениями.
# Hint: np.random

# TODO
randoms = np.random.rand(10,10)
print(randoms.max(), randoms.min(), sep = '\n')

0.9857925281757056
0.0003427727406855041


In [34]:
# Задание: создайте двумерный массив, заполненный так, что по периметру стоят единицы, а внутри нули. Hint: np.ones()
# shape =(10, 10)

# TODO
matrix = np.zeros((10, 10))
#matrix[0, :] = 1
#matrix[-1, :] = 1
#matrix[:, 0] = 1
#matrix[:, -1] = 1
#print(matrix)

#array = np.ones((10, 10))
#array[1:-1, 1:-1] = 0
#print(array)
matrix[::9, ::] = 1
matrix[::, ::9] = 1
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [53]:
# Задание: из каждой строки матрицы вычтите ее среднее. Hint: метод np.mean(), передаем в него аргумент axis
X = np.arange(1, 10, 1)
X = np.reshape(X, (3, 3))
print(X)

# TODO
avg = np.mean(X, axis = 1).reshape(3,1) #, keepdims=True)
print(avg)
Y = X - avg
print(Y)
(3, 3), (1, 3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2.]
 [5.]
 [8.]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


((3, 3), (1, 3))

In [55]:
# Задание: в заданном одномерном массиве вычтите eдиницу из каждого элемента больше 3 и меньше 8
Z = np.arange(11)
print(Z)

# TODO
Z[(Z > 3) & (Z < 8)] -= 1
Z

[ 0  1  2  3  4  5  6  7  8  9 10]


array([ 0,  1,  2,  3,  3,  4,  5,  6,  8,  9, 10])

In [ ]:
# Временные данные в numpy: np.datetime64, np.timedelta64
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(np.timedelta64(1))
print(yesterday, today, tomorrow)

# Временные последовательности
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

# pandas

In [62]:
# Датасет
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

data = pd.read_csv(url, sep = '\t')
data.head(3)

order_id  quantity                     item_name choice_description  \
0         1         1  Chips and Fresh Tomato Salsa                NaN   
1         1         1                          Izze       [Clementine]   
2         1         1              Nantucket Nectar            [Apple]   

  item_price  
0     $2.39   
1     $3.39   
2     $3.39

In [63]:
data.shape

(4622, 5)

In [64]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   order_id            4622 non-null   int64 
 1   quantity            4622 non-null   int64 
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB


In [ ]:
data.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [65]:
data['item_name'].unique()

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos

In [69]:
# Фильтрация
salad = data[data.item_name == "Veggie Salad Bowl"]

#len(salad)
salad.head()

order_id  quantity          item_name  \
186        83         1  Veggie Salad Bowl   
295       128         1  Veggie Salad Bowl   
455       195         1  Veggie Salad Bowl   
496       207         1  Veggie Salad Bowl   
960       394         1  Veggie Salad Bowl   

                                    choice_description item_price  
186  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $11.25   
295  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...    $11.25   
455  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $11.25   
496  [Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...    $11.25   
960  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75

In [70]:
# Задание: найдите в скольких заказах напиток в банке (Canned Soda) заказали больше одного раза. Hint: метод unique() / nunique()
# 1. выбрать строки, в которых есть canned soda и его количество больше 2
# 2. найти уникальные номера заказов
# 3. посчитать их количество

# TODO
soda = data[data.item_name == "Canned Soda"]
soda = soda[soda.quantity > 1]
#soda = data[(data.item_name == "Canned Soda") & (data[data.quantity > 1])]
soda.order_id.nunique()

18

In [ ]:
# Самые популярные заказанные блюда
data.item_name.value_counts()[:5]

Chicken Bowl           726
Chicken Burrito        553
Chips and Guacamole    479
Steak Burrito          368
Canned Soft Drink      301
Name: item_name, dtype: int64

In [3]:
# Конвертация типов и применение функции к столбцу
data.item_price.dtype

dtype('O')

In [71]:
dollarizer = lambda x: float(x[1:-1])
data.item_price = data.item_price.map(dollarizer)

In [72]:
data.item_price.dtype

dtype('float64')

In [76]:
# Задание: найдите суммарную выручку по всем заказам (подсказка -- используйте функцию sum())

# TODO
data['money'] = data['quantity'] * data['item_price']

print('Revenue was: $' + str(data['money'].sum()))

Revenue was: $39237.02


In [ ]:
# Группировка и сортировка
c = data.groupby('choice_description')['quantity'].sum().reset_index()
c.columns = ['choice_description', 'total_quantity']
c = c.sort_values(['total_quantity'], ascending=False)
c.head(1)

In [ ]:
# Задание: найдите среднюю выручку за заказ

# TODO


In [ ]:
# Задание: найдите самое дорогое заказанное блюдо

# TODO


In [ ]:
# Строим гистограмму топ 5 заказанных блюд

df = data.item_name.value_counts()[:5]

df.plot(kind='bar')

# Set the title and labels
plt.xlabel('Items')
plt.ylabel('Number of Times Ordered')
plt.title('Most ordered items')

# show the plot
plt.show()

In [ ]:
# Строим scatter plot, в котром по оси X будут стоимости заказов, а по оси Y -- количество раз этих заказов

order = data.groupby('order_id')['revenue'].sum().reset_index()
order.columns = ['order_id', 'revenue']

num_orders = order.groupby('revenue')['order_id'].count().reset_index()
num_orders.columns = ['revenue', 'num_orders']

plt.scatter(x = num_orders['revenue'], y = num_orders['num_orders'], s = 10, c = 'green')

plt.xlabel('Order Revenue')
plt.ylabel('Number of orders')
plt.title('Number of orders per order revenue')
plt.ylim(0)